### ISSUE TITLE
Whats the status?

### ISSUE THREAD

**Issue by ghost** [w3gh/ghost.js#1]
How much is done already and what is missing?
I'm interested picking it up and continue on that.

I'm myself mostly a frontend dev and love nodejs, so its even better for me than c++ :see_no_evil:

**Comment by JiLiZART** [comment]
Oh, it's in very early stage, I doing it on free time.
Currently i have issues with stormlib and bncsutil bindings to nodejs, if you could help, it will be good..

**Comment by ghost** [comment]
Okay, good to know.
I'm currently also pretty busy, i should be free in the middle of October to work a bit :-)

**Comment by JiLiZART** [comment]
@Grief-Code currently I got it work, bot can connect to the Battle.net and chat

**Comment by ghost** [comment]
@JiLiZART That's pretty good. So it can be used as channel bot already.
How did you bypass the cd key key auth? It was in bncsutil afaik.

**Comment by JiLiZART** [comment]
I use `libbncsuti` through node-ffi inteface and call C code inside js for bypassing auth checks

**Comment by ghost** [comment]
Okay, and this is not possible for stormlib? I've read that this is the main usage for such things.

**Comment by JiLiZART** [comment]
I will try it later :)

**Comment by ghost** [comment]
Amazing :-) Keep me informed about that.
Would it be able fo your to join discord channel for easier interactions?
https://discord.gg/tE6nb
