### ISSUE TITLE
Как скомпилить libbncsutil.so?

### ISSUE THREAD

**Issue by TemKaSD** [w3gh/ghost.js#3]
Здравствуйте. Пробовал скопировать из обычного ghost и вашего с раздела /src/bncsutil/ не хочет, пишет ошибку символической ссылки.

**Comment by JiLiZART** [comment]
А есть полный лог что пишет?

**Comment by linyx-omg** [comment]
Проблема все еще актуальна. Ни одна либа не подошла, все время выдает какие-либо ошибки, например не видит некоторые функции.

Пробовал на win 10, ubuntu 18, debian 10.

@JiLiZART, есть возможность помочь разобраться?

Соберу в любой из выше перечисленных ОС либку, ссылку на которую предоставишь, покажу лог запуска бота с ошибкой

![image](https://user-images.githubusercontent.com/16743128/91641120-082ece80-ea2b-11ea-8300-9d07696fb19d.png)

на скрине последняя попытка запустить с либкой из твоего проекта bncsutil-node...

**Comment by linyx-omg** [comment]
После последнего апдейта, попробовал запустить с либкой libbncsutil.so из репо, но получал ту же ошибку. Пересобрал из офф репозитория bncsutil.so и все заработало. Таже самая фигня с StormLib

**Comment by JiLiZART** [comment]
Скоро запушу Dockerfile в котором 100% будет все собираться и работать

**Comment by JiLiZART** [comment]
Добавил github actions, https://github.com/w3gh/ghost.js/actions теперь всегда стабильный docker контейнер будет
